spring:
  freemarker:
    request-context-attribute: req
    suffix: .ftl
    content-type: text/html
    cache: false
    template-loader-path: classpath:/templates/
    charset: UTF-8
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
  datasource:
    druid:
      username: root
      password: 20001003
      url: jdbc:mysql://127.0.0.1:3306/bootvue?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      exclude: static/**,templates/**
      enabled: true
      additional-paths: src/main/**
    thymeleaf:
      cache:
        false
      prefix: classpath:/templates/common,classpath:/templates/system
      suffix: .ftl
    remote:
      debug:
        local-port: 8888
server:
  port: 8888
thymeleaf:
  cache: false
  encoding: UTF-8
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML5
mybatis:
  type-aliases-package: laki.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


